version: "2.2"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: kaddemuniversite:latest
    container_name: kaddemuniversite
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
